// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Contactus5AugTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void contactus5Aug() {
    driver.get("https://www.tops-int.com/contact-us/");
    driver.manage().window().setSize(new Dimension(1050, 708));
    driver.findElement(By.linkText("Contact us")).click();
    driver.findElement(By.id("inq_name")).click();
    driver.findElement(By.id("inq_name")).sendKeys("hetu");
    driver.findElement(By.id("inq_email")).sendKeys("hetu@yopmail.com");
    driver.findElement(By.id("inq_contact")).click();
    driver.findElement(By.id("inq_contact")).sendKeys("8787878750");
    driver.switchTo().frame(1);
    driver.findElement(By.cssSelector("img")).click();
  }
}
